create database DBHAVEHD


CREATE TABLE CATEGORY
(
 ID INT IDENTITY PRIMARY KEY,
  NAME NVARCHAR(50)
)

CREATE TABLE PRODUCT
(
  ID INT IDENTITY PRIMARY KEY,
  NAME NVARCHAR(50),
  PRICE FLOAT,
  IMAGE NVARCHAR(225),
  DESCRIPTION NVARCHAR(225),
  CATEGORY_ID  INT

  FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID)
)

create table USERS
(
  ID INT IDENTITY PRIMARY KEY,
  USERNAME NVARCHAR(50),
  NAME NVARCHAR(50),
  PASSWORD NVARCHAR(50),
  REMEMBERME bit,
  ROLE NVARCHAR(30)
)


CREATE TABLE ORDERS
(
  ID INT IDENTITY PRIMARY KEY,
  ID_USERS INT,
  DATE     DATETIME,
  ADDRESS  NVARCHAR(100),
  FOREIGN KEY(ID_USERS) REFERENCES Users(ID)
)
CREATE TABLE ORDERDETAILS
(
  ID INT IDENTITY PRIMARY KEY,
  ORDER_ID  INT,
  PRODUCT_ID INT, 
  PRICE FLOAT,
  QUANTITY INT

  FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ID),
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID)
)


CREATE TABLE HOADON
(
  ID INT IDENTITY PRIMARY KEY,
  ID_USERS  INT,
  NGAYTAO DATETIME, 
  NGAYTHANHTOAN DATETIME,
  TENNGUOINHAN  NVARCHAR(50)

 FOREIGN KEY(ID_USERS) REFERENCES Users(ID)
  
)


CREATE TABLE HOADONCT
(
  ID INT IDENTITY PRIMARY KEY,
  ID_HOADON  INT,
  PRODUCT_ID INT, 
  SOLUONG INT,
  DONGIA FLOAT

  FOREIGN KEY(ID_HOADON) REFERENCES HOADON(ID),
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID)
  
)

